# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info/cert.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from info import common_pb2 as info_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finfo/cert.proto\x12\x13org.lfedge.eve.info\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11info/common.proto\"\xf5\x03\n\x08\x43\x65rtInfo\x12$\n\x1c\x63\x65rt_enrollment_profile_name\x18\x01 \x01(\t\x12;\n\x07subject\x18\x02 \x01(\x0b\x32*.org.lfedge.eve.info.CertDistinguishedName\x12:\n\x06issuer\x18\x03 \x01(\x0b\x32*.org.lfedge.eve.info.CertDistinguishedName\x12\x0f\n\x07san_dns\x18\x04 \x03(\t\x12\x0e\n\x06san_ip\x18\x05 \x03(\t\x12\x0f\n\x07san_uri\x18\x06 \x03(\t\x12\x11\n\tsan_email\x18\x07 \x03(\t\x12\x33\n\x0fissue_timestamp\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x38\n\x14\x65xpiration_timestamp\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1c\n\x14renew_period_percent\x18\n \x01(\r\x12\x1a\n\x12sha256_fingerprint\x18\x0b \x01(\t\x12/\n\x06status\x18\x0c \x01(\x0e\x32\x1f.org.lfedge.eve.info.CertStatus\x12+\n\x03\x65rr\x18\r \x01(\x0b\x32\x1e.org.lfedge.eve.info.ErrorInfo\"\xb4\x01\n\x15\x43\x65rtDistinguishedName\x12\x13\n\x0b\x63ommon_name\x18\x01 \x01(\t\x12\x15\n\rserial_number\x18\x02 \x01(\t\x12\x14\n\x0corganization\x18\x03 \x03(\t\x12\x1b\n\x13organizational_unit\x18\x04 \x03(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x03(\t\x12\x19\n\x11state_or_province\x18\x06 \x03(\t\x12\x10\n\x08locality\x18\x07 \x03(\t*\x93\x02\n\nCertStatus\x12\x1b\n\x17\x43\x45RT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15\x43\x45RT_STATUS_AVAILABLE\x10\x01\x12\x17\n\x13\x43\x45RT_STATUS_PENDING\x10\x02\x12\x1f\n\x1b\x43\x45RT_STATUS_RENEWAL_PENDING\x10\x03\x12\x17\n\x13\x43\x45RT_STATUS_EXPIRED\x10\x04\x12\x17\n\x13\x43\x45RT_STATUS_REVOKED\x10\x05\x12!\n\x1d\x43\x45RT_STATUS_ENROLLMENT_FAILED\x10\x06\x12\x1e\n\x1a\x43\x45RT_STATUS_RENEWAL_FAILED\x10\x07\x12\x1e\n\x1a\x43\x45RT_STATUS_INVALID_CONFIG\x10\x08\x42\x39\n\x13org.lfedge.eve.infoZ\"github.com/lf-edge/eve-api/go/infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'info.cert_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023org.lfedge.eve.infoZ\"github.com/lf-edge/eve-api/go/info'
  _globals['_CERTSTATUS']._serialized_start=780
  _globals['_CERTSTATUS']._serialized_end=1055
  _globals['_CERTINFO']._serialized_start=93
  _globals['_CERTINFO']._serialized_end=594
  _globals['_CERTDISTINGUISHEDNAME']._serialized_start=597
  _globals['_CERTDISTINGUISHEDNAME']._serialized_end=777
# @@protoc_insertion_point(module_scope)
