# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile/signal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14profile/signal.proto\x12\x16org.lfedge.eve.profile\"I\n\x06Signal\x12?\n\x0fpending_changes\x18\x01 \x03(\x0e\x32&.org.lfedge.eve.profile.ConfigEndpoint*\xeb\x01\n\x0e\x43onfigEndpoint\x12\x1f\n\x1b\x43ONFIG_ENDPOINT_UNSPECIFIED\x10\x00\x12!\n\x1d\x43ONFIG_ENDPOINT_LOCAL_PROFILE\x10\x01\x12\x19\n\x15\x43ONFIG_ENDPOINT_RADIO\x10\x02\x12\x1c\n\x18\x43ONFIG_ENDPOINT_APP_INFO\x10\x03\x12!\n\x1d\x43ONFIG_ENDPOINT_APP_BOOT_INFO\x10\x04\x12\x1c\n\x18\x43ONFIG_ENDPOINT_DEV_INFO\x10\x05\x12\x1b\n\x17\x43ONFIG_ENDPOINT_NETWORK\x10\x06\x42?\n\x16org.lfedge.eve.profileZ%github.com/lf-edge/eve-api/go/profileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile.signal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026org.lfedge.eve.profileZ%github.com/lf-edge/eve-api/go/profile'
  _globals['_CONFIGENDPOINT']._serialized_start=124
  _globals['_CONFIGENDPOINT']._serialized_end=359
  _globals['_SIGNAL']._serialized_start=48
  _globals['_SIGNAL']._serialized_end=121
# @@protoc_insertion_point(module_scope)
