# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/scep.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evecommon import acipherinfo_pb2 as evecommon_dot_acipherinfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63onfig/scep.proto\x12\x15org.lfedge.eve.config\x1a\x1b\x65vecommon/acipherinfo.proto\"\xe5\x01\n\x0bSCEPProfile\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\x12\x10\n\x08scep_url\x18\x02 \x01(\t\x12\x1c\n\x14use_controller_proxy\x18\x03 \x01(\x08\x12\x43\n\x17scep_challenge_password\x18\x04 \x01(\x0b\x32\".org.lfedge.eve.common.CipherBlock\x12\x13\n\x0b\x63\x61_cert_pem\x18\x05 \x03(\x0c\x12\x36\n\x0b\x63sr_profile\x18\x06 \x01(\x0b\x32!.org.lfedge.eve.config.CSRProfile\"\xd9\x02\n\nCSRProfile\x12\x13\n\x0b\x63ommon_name\x18\x01 \x01(\t\x12\x14\n\x0corganization\x18\x02 \x01(\t\x12\x1b\n\x13organizational_unit\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x10\n\x08locality\x18\x06 \x01(\t\x12\x0f\n\x07san_dns\x18\n \x03(\t\x12\x0e\n\x06san_ip\x18\x0b \x03(\t\x12\x0f\n\x07san_uri\x18\x0c \x03(\t\x12\x11\n\tsan_email\x18\r \x03(\t\x12\x1c\n\x14renew_period_percent\x18\x14 \x01(\r\x12\x30\n\x08key_type\x18\x15 \x01(\x0e\x32\x1e.org.lfedge.eve.config.KeyType\x12<\n\x0ehash_algorithm\x18\x16 \x01(\x0e\x32$.org.lfedge.eve.config.HashAlgorithm*\xb3\x01\n\x07KeyType\x12\x18\n\x14KEY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11KEY_TYPE_RSA_2048\x10\x01\x12\x15\n\x11KEY_TYPE_RSA_3072\x10\x02\x12\x15\n\x11KEY_TYPE_RSA_4096\x10\x03\x12\x17\n\x13KEY_TYPE_ECDSA_P256\x10\n\x12\x17\n\x13KEY_TYPE_ECDSA_P384\x10\x0b\x12\x17\n\x13KEY_TYPE_ECDSA_P521\x10\x0c*\x80\x01\n\rHashAlgorithm\x12\x1e\n\x1aHASH_ALGORITHM_UNSPECIFIED\x10\x00\x12\x19\n\x15HASH_ALGORITHM_SHA256\x10\x01\x12\x19\n\x15HASH_ALGORITHM_SHA384\x10\x02\x12\x19\n\x15HASH_ALGORITHM_SHA512\x10\x03\x42=\n\x15org.lfedge.eve.configZ$github.com/lf-edge/eve-api/go/configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config.scep_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025org.lfedge.eve.configZ$github.com/lf-edge/eve-api/go/config'
  _globals['_KEYTYPE']._serialized_start=654
  _globals['_KEYTYPE']._serialized_end=833
  _globals['_HASHALGORITHM']._serialized_start=836
  _globals['_HASHALGORITHM']._serialized_end=964
  _globals['_SCEPPROFILE']._serialized_start=74
  _globals['_SCEPPROFILE']._serialized_end=303
  _globals['_CSRPROFILE']._serialized_start=306
  _globals['_CSRPROFILE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
