# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/scep.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proxy/scep.proto\x12\x14org.lfedge.eve.proxy\"\xf0\x01\n\x10SCEPProxyRequest\x12\x19\n\x11scep_profile_name\x18\x01 \x01(\t\x12\x36\n\toperation\x18\x02 \x01(\x0e\x32#.org.lfedge.eve.proxy.SCEPOperation\x12\x0f\n\x07message\x18\x03 \x01(\x0c\x12\x35\n\x0bhttp_method\x18\x04 \x01(\x0e\x32 .org.lfedge.eve.proxy.HTTPMethod\x12\x41\n\x12http_header_fields\x18\x05 \x03(\x0b\x32%.org.lfedge.eve.proxy.HTTPHeaderField\".\n\x0fHTTPHeaderField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xe8\x01\n\x11SCEPProxyResponse\x12\x19\n\x11scep_profile_name\x18\x01 \x01(\t\x12\x36\n\toperation\x18\x02 \x01(\x0e\x32#.org.lfedge.eve.proxy.SCEPOperation\x12\x0f\n\x07message\x18\x03 \x01(\x0c\x12\x18\n\x10http_status_code\x18\x04 \x01(\r\x12\x41\n\x12http_header_fields\x18\x05 \x03(\x0b\x32%.org.lfedge.eve.proxy.HTTPHeaderField\x12\x12\n\nerror_body\x18\x06 \x01(\x0c*\xb4\x01\n\rSCEPOperation\x12\x1e\n\x1aSCEP_OPERATION_UNSPECIFIED\x10\x00\x12\x1e\n\x1aSCEP_OPERATION_GET_CA_CAPS\x10\x01\x12\x1e\n\x1aSCEP_OPERATION_GET_CA_CERT\x10\x02\x12#\n\x1fSCEP_OPERATION_GET_NEXT_CA_CERT\x10\x03\x12\x1e\n\x1aSCEP_OPERATION_PKI_MESSAGE\x10\x04*T\n\nHTTPMethod\x12\x1b\n\x17HTTP_METHOD_UNSPECIFIED\x10\x00\x12\x13\n\x0fHTTP_METHOD_GET\x10\x01\x12\x14\n\x10HTTP_METHOD_POST\x10\x02\x42;\n\x14org.lfedge.eve.proxyZ#github.com/lf-edge/eve-api/go/proxyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.scep_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.lfedge.eve.proxyZ#github.com/lf-edge/eve-api/go/proxy'
  _globals['_SCEPOPERATION']._serialized_start=569
  _globals['_SCEPOPERATION']._serialized_end=749
  _globals['_HTTPMETHOD']._serialized_start=751
  _globals['_HTTPMETHOD']._serialized_end=835
  _globals['_SCEPPROXYREQUEST']._serialized_start=43
  _globals['_SCEPPROXYREQUEST']._serialized_end=283
  _globals['_HTTPHEADERFIELD']._serialized_start=285
  _globals['_HTTPHEADERFIELD']._serialized_end=331
  _globals['_SCEPPROXYRESPONSE']._serialized_start=334
  _globals['_SCEPPROXYRESPONSE']._serialized_end=566
# @@protoc_insertion_point(module_scope)
